[tool.poetry]
name = "peanuts-bot"
version = "2.0.0"
description = ""
authors = ["Shajesh Jegatheeswaran <shajesh.14@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "peanuts_bot"}]

[tool.poetry.dependencies]
python = "3.10.5"
discord-py-interactions = "5.6.0"
aiohttp = "3.8.4"
async-lru = "2.0.2"
flask = "2.3.2"
matplotlib = "3.7.1"
python-dotenv = "0.20.0"


[tool.poetry.group.dev.dependencies]
black = "22.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
