name: Deploy shagbot
on:
  workflow_call:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**Makefile'

jobs:
  deploy:
    name: Deploy Bot
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tool Versions
        id: versions
        run: |
          echo "python=$(cat .tool-versions | grep -w "python" | cut -d ' ' -f2)" >> "$GITHUB_OUTPUT"
          echo "poetry=$(cat .tool-versions | grep -w "poetry" | cut -d ' ' -f2)" >> "$GITHUB_OUTPUT"
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ steps.versions.outputs.python }}"
      - name: Poetry
        run: python3 -m pip install poetry=="${{ steps.versions.outputs.poetry }}"
      - name: CI Script Dependencies
        run: poetry install --only=ci
      - name: Temp Test Build
        run: |
          poetry run python --version
          poetry run pip list
      # - name: Deploy Hook
      #   run: curl -X POST ${{ secrets.DEPLOY_HOOK }}
