name: Deploy shagbot
on:
  workflow_call:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**Makefile'

jobs:
  deploy:
    name: Trigger Deploy Hook
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: curl deploy hook
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}